# Generated by Django 3.1.5 on 2021-04-29 05:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('predict', '0002_auto_20210408_2250'),
    ]

    operations = [
        migrations.AddField(
            model_name='disease',
            name='numericConvert',
            field=models.CharField(max_length=1000, null=True),
        ),
    ]
